//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogpost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blogpost()
        {
            this.comments = new HashSet<comment>();
            this.userlikes = new HashSet<userlike>();
        }
    
        public int postId { get; set; }
        public int blogID { get; set; }
        public string employeeID { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public string ImageURL { get; set; }
    
        public virtual blog blog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual employeedetail employeedetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userlike> userlikes { get; set; }
    }
}
