//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.secondcomments = new HashSet<secondcomment>();
        }
    
        public int commentID { get; set; }
        public int postId { get; set; }
        public string employeeID { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> cmtTime { get; set; }
        public string ImageURL { get; set; }
    
        public virtual blogpost blogpost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<secondcomment> secondcomments { get; set; }
    }
}
