//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeedetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeedetail()
        {
            this.blogposts = new HashSet<blogpost>();
            this.blogs = new HashSet<blog>();
            this.contactemployeeinfoes = new HashSet<contactemployeeinfo>();
            this.workhistories = new HashSet<workhistory>();
            this.qualifications = new HashSet<qualification>();
            this.salaryinfoes = new HashSet<salaryinfo>();
            this.timeinfoes = new HashSet<timeinfo>();
        }
    
        public string employeeID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string avtUrl { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogpost> blogposts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog> blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactemployeeinfo> contactemployeeinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workhistory> workhistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qualification> qualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salaryinfo> salaryinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeinfo> timeinfoes { get; set; }
    }
}
