//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Pushcmt
    {
        public int postID { get; set; }
        public string Contentcmt { get; set; }
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
  
        public HttpPostedFileBase ImageFilecmt { get; set; }
    }
}
