//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryinfo
    {
        public int idSalaryinfo { get; set; }
        public string employeeID { get; set; }
        public Nullable<int> monthlySalary { get; set; }
        public Nullable<int> monneyCurrency { get; set; }
        public Nullable<int> monneyDeductions { get; set; }
        public Nullable<int> monneyInsurance { get; set; }
    
        public virtual employeedetail employeedetail { get; set; }
    }
}
