//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secondcomment
    {
        public int secondcmt { get; set; }
        public int commentID { get; set; }
        public string employeeIDcmt { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> cmtTime { get; set; }
        public string ImageURL { get; set; }
    
        public virtual comment comment { get; set; }
    }
}
