//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VER_CONNECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlike
    {
        public int likeID { get; set; }
        public int postID { get; set; }
        public string employeeID { get; set; }
    
        public virtual blogpost blogpost { get; set; }
    }
}
